name: SWATtest
version: '${project.version}'
main: me.rqmses.swattest.SWATtest
commands:
  fly:
    description:  Schaltet den Flug-Modus um.
    usage: /<command>
  heal:
    description:  Regeneriert den Spieler voll.
    usage: /<command>
  warp:
    description: Teleportiert den Spieler an einen gewünschten Ort.
    usage: /<command> <target>
  equip:
    description: Wählt ein Equip aus.
    usage: /<command> <equip>
  spawn:
    description: Setzt deinen Spawnpunkt neu.
    usage: /<command>
  use:
    description: Nimm die ausgewählte Droge.
    usage: /<command> <drug>
  team:
    description: Wähle ein Team aus.
    usage: /<command> <team>
  teamname:
    description: Ändert den Namen eines Teams.
    usage: /<command> <teamname1> <teamname2>
  camera:
    description: Schalte den Kamera-Modus um.
    usage: /<command>
  bombe:
    description: Platziere eine temporäre Bombe.
    usage: /<command>
  navi:
    description: Zeige die Richtung deines Ziels an.
    usage: /<command> <target>
  cooldown:
    description: Setzt sämtliche Reload-Zeiten zurück.
    usage: /<command>
  resetdata:
    description: Setzt den Speicherstand zurück.
    usage: /<command>
  trainingsbot:
    description: Spawnt eine Trainings-KI.
    usage: /<command> <name>
  abaimbot:
    description: Spawnt eine Abaim-KI.
    usage: /<command> <name>
  luftlinie:
    description: Stellt die Navidistanz als Luftlinie dar.
    usage: /<command>
  leitfaden:
    description: Öffnet eine analoge Unterstützung für Spieler.
    usage: /<command>
  car:
    description: Spawnt und steuert ein Auto.
    usage: /<command> <argument>
  inv:
    description: Gibt Zugriff auf das Inventar eines anderen Spielers.
    usage: /<command> <player>
  vanish:
    description: Versteckt den Spieler vor allen Systemen.
    usage: /<command>
  admin:
    description: Gibt eine Liste an Admins aus, beziehungsweise fügt hinzu.
    usage: /<command> <name>